### ISSUE TITLE
docs: accordionitem

### ISSUE THREAD

**Issue by gioboa** [qwikifiers/qwik-storefront-ui#10]
API and Source Code tabs are empty ~~https://qwik-storefront-ui.vercel.app/qwik/components/accordionitem~~
https://qwik-storefront-ui.pages.dev/qwik/components/accordionitem

<img width="370" alt="Screenshot 2023-10-10 at 11 19 57" src="https://github.com/qwikifiers/qwik-storefront-ui/assets/35845425/c1587c6a-b58d-4265-b7c4-54b9254b60b4">

**Comment by thecoder93** [comment]
I will work on it.
