### ISSUE TITLE
ProgressLinear playground not working correctly

### ISSUE THREAD

**Issue by thecoder93** [qwikifiers/qwik-storefront-ui#21]
![image](https://github.com/qwikifiers/qwik-storefront-ui/assets/3246694/d6232e6e-e20e-42f0-b35b-f8e0be0cc87e)

**Comment by gioboa** [comment]
Fixed with https://github.com/qwikifiers/qwik-storefront-ui/commit/1bcecb2045d034ac6a6fc65c38bf7e32c4f7c29b
