### ISSUE TITLE
Typescript Error: "Could not find a declaration file for module 'qwik-storefront-ui'"

### ISSUE THREAD

**Issue by sebacc92** [qwikifiers/qwik-storefront-ui#53]
### Problem Description

I'm encountering a TypeScript error when trying to import components from the `qwik-storefront-ui` library. The error message is as follows:

![image](https://github.com/user-attachments/assets/f8ff5a19-17ef-45ec-b109-27c58042e116)

```
Could not find a declaration file for module 'qwik-storefront-ui'. '/home/seba/devs/pactgeo/pactgeo-webapp/node_modules/qwik-storefront-ui/index.qwik.mjs' implicitly has an 'any' type.
  There are types at '/home/seba/devs/pactgeo/pactgeo-webapp/node_modules/qwik-storefront-ui/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'qwik-storefront-ui' library may need to update its package.json or typings.
```

### Steps to Reproduce

1. Install the `qwik-storefront-ui` package in a Qwik project.
2. Attempt to import a component from the library (e.g., `import { SfButton } from 'qwik-storefront-ui';`).
3. Observe the TypeScript error.

### Temporary Workaround

Adding `"types": "./index.d.ts"` directly within the `exports` section of the `package.json` in the `qwik-storefront-ui` module resolves the issue. However, this is a manual fix that might get overwritten with updates.

![image](https://github.com/user-attachments/assets/b424e9b2-20a0-4d27-9369-9b3190c48ee4)

### Suggested Solution

It seems that the issue could be resolved by updating the `package.json` in the `qwik-storefront-ui` module to include a proper reference to the TypeScript declaration file within the `exports` section.

### Environment

- **Qwik Version:** 1.8.0
- **qwik-storefront-ui Version:** 0.0.8
- **TypeScript Version:** 5.5.4

Please let me know if any additional information is needed. Thank you for your assistance!

**Comment by gioboa** [comment]
Thanks for your feedback @sebacc92 
I'll check it out 👍

**Comment by gioboa** [comment]
ad54a9aaa7d6351d2c1f9efb85d1fd6fad4a69b2 fixed the problem. [v.0.0.10](https://www.npmjs.com/package/qwik-storefront-ui/v/0.0.10) is working fine.
