### ISSUE TITLE
[bug] Demo Link for getting started does not work  

### ISSUE THREAD

**Issue by sarvex** [qwikifiers/qwik-storefront-ui#6]
https://qwik-storefront-ui.pages.dev/qwik/getting-started.html returns 404

**Comment by gioboa** [comment]
Hi, thanks for your feedback, we are still working on it 😊

**Comment by gioboa** [comment]
The idea is to adapt the official documentation to the Qwik integration, I've included the official documentation in apps/docs folder but I'm still struggling to get it to work

**Comment by gioboa** [comment]
The new documentation is here https://qwik-storefront-ui.vercel.app/ 😉
